# Generated by Django 6.0.6 on 2026-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dias', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=20)),
                ('cupo_max', models.IntegerField()),
                ('cupo_disponible', models.IntegerField()),
            ],
        ),
    ]
